apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: aws-secret-injector
  name: aws-secret-injector
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: aws-secret-injector
  template:
    metadata:
      labels:
        app: aws-secret-injector
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1337
        runAsGroup: 1337
      volumes:
      - name: certs
        secret:
          secretName: aws-secret-injector-tls
      containers:
      - name: admission-controller
        image: erousseau/aws-secret-injector/admission-controller:v1.6
        volumeMounts:
        - name: certs
          mountPath: /tls
          readOnly: true
        args:
        - --tls-cert-file=/tls/tls.crt
        - --tls-private-key-file=/tls/tls.key
        - --init-container-image=erousseau/aws-secret-injector/init-container:v1.6
        ports:
        - containerPort: 8443
        imagePullPolicy: Always
        securityContext:
          privileged: false
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 256Mi