{{ if .Values.createPodDisruptionBudget }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  labels:
    app: aws-secret-injector
  name: aws-secret-injector
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: aws-secret-injector
{{ end }}
      