name: Build Latest

on:
  push:
    branches:
    - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
      - name: Build 🔧
        run: |
          docker build init-container -t docker.io/erousseau/aws-secrets-injector-init-container:latest
          docker build admission-controller -t docker.io/erousseau/aws-secrets-injector-adm-controller:latest
      - name: Push 🚀
        env:
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          docker push docker.io/erousseau/aws-secrets-injector-init-container:latest
          docker push docker.io/erousseau/aws-secrets-injector-adm-controller:latest